apiVersion: batch/v1
kind: Job
metadata:
  name: jmeter-job
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: jmeter
        image: justb4/jmeter:latest
        imagePullPolicy: IfNotPresent
        command:
        - jmeter
        - -n
        - -t
        - /tests/Ephemeral_cicd.jmx
        - -l
        - /results/results.jtl
        - -e
        - -o
        - /results/report
        volumeMounts:
        - name: jmeter-script
          mountPath: /tests
        - name: jmeter-results
          mountPath: /results
      volumes:
      - name: jmeter-script
        configMap:
          name: jmeter-config
      - name: jmeter-results
        emptyDir: {}